name: Hello World
on: push
jobs:
  say_hello:
    name: Say Hello World
    runs-on: ubuntu-18.04
    steps:
      - name: echo
        run: |
          echo 'Hello'
          echo 'World'
  build:
    name: Build Symfony Project
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Composer Install
        uses: php-actions/composer@v6