name: Tags
on:
  push:
    tags:
      - v*
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Version
        id: verion
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo ::set-output name=VERSION::${TAG}
      - name: Deploy
        run: echo "deploy version '${{ setps.version.outputs.VERSION }}'"